[package]
name = "demo2"
version = "0.1.34"
authors = ["Your Name <lukasz.woznicki@softwareag.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
