name: hosted-post-merge

on:
  # Only run, when a pull request is merged.
#   push:
#    branches: [ main ]
  # We need to use pull_request event as only then we can determine the branch it came from and therefore determine what to update patch or minor.
  pull_request:
    types: [closed]

env:
  CARGO_TERM_COLOR: always

jobs:
  versioning:
#     if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

#       - name: Enable cache  
#         uses: actions/cache@v2
#         with:
#           path: |
#             ~/.cargo/registry
#             ~/.cargo/git
#             target
#           key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
#       - name: Install cargo-deb
#         uses: actions-rs/cargo@v1
#         with:
#           command: install
#           args: cargo-deb

#       - name: Build tedge debian package
#         uses: actions-rs/cargo@v1
#         with:
#           command: deb
#           args: -p tedge

#       - name: Build tedge_mapper debian package
#         uses: actions-rs/cargo@v1
#         with:
#           command: deb
#           args: -p tedge_mapper

      - name: Install cargo-release
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-release

      - name: Increment version and tag
        uses: actions-rs/cargo@v1
        with:
          command: release
#           args: patch --dry-run --skip-publish -vv --no-dev-version
          args: patch --skip-publish -vv --no-dev-version --no-confirm
