name: hosted-post-merge

on:
  # Only run, when a pull request is merged.
#   push:
#    branches: [ main ]
  # We need to use pull_request event as only then we can determine the branch it came from and therefore determine what to update patch or minor.
  pull_request:
    types: [closed]

env:
  CARGO_TERM_COLOR: always

jobs:
  versioning:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          git config --global user.email "version@actions.io"
          git config --global user.name "Versioneer"

      - uses: Swatinem/rust-cache@v1

      - name: Install cargo-release
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-release

      - name: Increment version and tag
        uses: actions-rs/cargo@v1
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          command: release
#           args: patch --dry-run --skip-publish -vv --no-dev-version
          args: patch --skip-publish -vv --no-dev-version --no-confirm
